"""
Database models for ATS-SMT Pro Trading Bot.
"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, ForeignKey, Enum, Text, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import enum

from backend.core.persistence.database import Base


class TradingMode(enum.Enum):
    PAPER = "paper"
    TESTNET = "testnet"
    LIVE = "live"


class OrderStatus(enum.Enum):
    SIGNAL_CREATED = "signal_created"
    ORDER_PENDING = "order_pending"
    ORDER_SUBMITTED = "order_submitted"
    ORDER_PARTIALLY_FILLED = "order_partially_filled"
    ORDER_FILLED = "order_filled"
    ORDER_CANCELLED = "order_cancelled"
    ORDER_REJECTED = "order_rejected"
    POSITION_OPEN = "position_open"
    POSITION_CLOSED = "position_closed"


class PositionSide(enum.Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class Exchange(Base):
    """Exchange configuration and status."""
    __tablename__ = "exchanges"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(50), unique=True, nullable=False)
    enabled = Column(Boolean, default=True)
    testnet = Column(Boolean, default=True)
    api_key_encrypted = Column(Text)
    api_secret_encrypted = Column(Text)
    passphrase_encrypted = Column(Text)
    rate_limit_per_second = Column(Float, default=10.0)
    is_connected = Column(Boolean, default=False)
    last_error = Column(Text)
    last_sync = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    symbols = relationship("Symbol", back_populates="exchange")
    orders = relationship("Order", back_populates="exchange")
    positions = relationship("Position", back_populates="exchange")


class Symbol(Base):
    """Trading symbol configuration per exchange."""
    __tablename__ = "symbols"

    id = Column(Integer, primary_key=True, autoincrement=True)
    exchange_id = Column(Integer, ForeignKey("exchanges.id"), nullable=False)
    canonical_symbol = Column(String(20), nullable=False)  # BTC/USDT
    exchange_symbol = Column(String(50), nullable=False)  # BTCUSDT, BTC/USDT:USDT, etc.
    is_available = Column(Boolean, default=True)
    is_active = Column(Boolean, default=True)
    min_qty = Column(Float, default=0.0)
    max_qty = Column(Float)
    qty_step = Column(Float, default=0.0)
    min_price = Column(Float, default=0.0)
    max_price = Column(Float)
    price_step = Column(Float, default=0.0)
    min_notional = Column(Float, default=0.0)
    price_precision = Column(Integer, default=8)
    qty_precision = Column(Integer, default=8)
    unavailable_reason = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    exchange = relationship("Exchange", back_populates="symbols")
    candles = relationship("Candle", back_populates="symbol")
    signals = relationship("Signal", back_populates="symbol")
    positions = relationship("Position", back_populates="symbol")
    orders = relationship("Order", back_populates="symbol")

    __table_args__ = (
        {'sqlite_autoincrement': True}  # For SQLite compatibility in tests
    )


class Candle(Base):
    """OHLCV candle data."""
    __tablename__ = "candles"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol_id = Column(Integer, ForeignKey("symbols.id"), nullable=False)
    timeframe = Column(String(10), nullable=False)  # 30m, 4h, 1d
    timestamp = Column(DateTime(timezone=True), nullable=False)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)
    is_closed = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    symbol = relationship("Symbol", back_populates="candles")

    __table_args__ = (
        {'sqlite_autoincrement': True}
    )


class Signal(Base):
    """Trading signal generated by strategy."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(String(100), unique=True, nullable=False)  # UUID
    symbol_id = Column(Integer, ForeignKey("symbols.id"), nullable=False)
    exchange_id = Column(Integer, ForeignKey("exchanges.id"), nullable=False)
    timeframe = Column(String(10), nullable=False)
    action = Column(String(10), nullable=False)  # LONG, SHORT
    entry_price = Column(Float, nullable=False)
    sl_price = Column(Float, nullable=False)
    tp1_price = Column(Float)
    tp2_price = Column(Float)
    tp3_price = Column(Float)
    regime = Column(String(20))  # DEAD, RANGE, TREND
    votes = Column(Integer)  # 0-3
    htf_4h = Column(Integer)  # -1, 0, 1
    htf_1d = Column(Integer)  # -1, 0, 1
    adx_value = Column(Float)
    atr_value = Column(Float)
    volume_ratio = Column(Float)
    bos_detected = Column(Boolean, default=False)
    choch_detected = Column(Boolean, default=False)
    risk_pct = Column(Float, default=1.0)
    position_size = Column(Float)
    strategy_version = Column(String(20), default="SMT_PRO_V2")
    status = Column(String(20), default="created")  # created, processed, executed, cancelled
    processed = Column(Boolean, default=False)
    order_id = Column(Integer, ForeignKey("orders.id"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    symbol = relationship("Symbol", back_populates="signals")
    exchange = relationship("Exchange", back_populates="signals")
    order = relationship("Order", back_populates="signal")

    __table_args__ = (
        {'sqlite_autoincrement': True}
    )


class Order(Base):
    """Order placed on exchange."""
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, autoincrement=True)
    order_id = Column(String(100), unique=True, nullable=False)  # UUID for idempotency
    client_order_id = Column(String(100), unique=True)
    exchange_order_id = Column(String(100))
    symbol_id = Column(Integer, ForeignKey("symbols.id"), nullable=False)
    exchange_id = Column(Integer, ForeignKey("exchanges.id"), nullable=False)
    signal_id = Column(Integer, ForeignKey("signals.id"))
    position_id = Column(Integer, ForeignKey("positions.id"))
    side = Column(String(10), nullable=False)  # BUY, SELL
    order_type = Column(String(20), nullable=False)  # market, limit, stop
    quantity = Column(Float, nullable=False)
    price = Column(Float)
    avg_fill_price = Column(Float)
    filled_quantity = Column(Float, default=0.0)
    remaining_quantity = Column(Float)
    status = Column(Enum(OrderStatus), default=OrderStatus.ORDER_PENDING)
    fees = Column(Float, default=0.0)
    fee_currency = Column(String(20))
    reject_reason = Column(Text)
    strategy = Column(String(50), default="SMT_PRO_V2")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    submitted_at = Column(DateTime(timezone=True))
    filled_at = Column(DateTime(timezone=True))
    cancelled_at = Column(DateTime(timezone=True))

    symbol = relationship("Symbol", back_populates="orders")
    exchange = relationship("Exchange", back_populates="orders")
    signal = relationship("Signal", back_populates="order")
    position = relationship("Position", back_populates="orders")

    __table_args__ = (
        {'sqlite_autoincrement': True}
    )


class Position(Base):
    """Active or closed trading position."""
    __tablename__ = "positions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    position_id = Column(String(100), unique=True, nullable=False)  # UUID
    exchange_id = Column(Integer, ForeignKey("exchanges.id"), nullable=False)
    symbol_id = Column(Integer, ForeignKey("symbols.id"), nullable=False)
    side = Column(Enum(PositionSide), nullable=False)
    quantity = Column(Float, nullable=False)
    remaining_quantity = Column(Float, nullable=False)
    signal_entry = Column(Float, nullable=False)
    actual_entry = Column(Float, nullable=False)
    initial_risk = Column(Float, nullable=False)
    sl_price = Column(Float, nullable=False)
    tp1_price = Column(Float)
    tp2_price = Column(Float)
    tp3_price = Column(Float)
    tp1_hit = Column(Boolean, default=False)
    tp2_hit = Column(Boolean, default=False)
    tp3_hit = Column(Boolean, default=False)
    tp1_closed_qty = Column(Float, default=0.0)
    tp2_closed_qty = Column(Float, default=0.0)
    tp3_closed_qty = Column(Float, default=0.0)
    breakeven_active = Column(Boolean, default=False)
    trailing_active = Column(Boolean, default=False)
    trail_stop_price = Column(Float)
    strategy = Column(String(50), default="SMT_PRO_V2")
    regime = Column(String(20))
    votes = Column(Integer)
    strategy_params_snapshot = Column(JSON)  # Snapshot of params at position open
    is_open = Column(Boolean, default=True)
    opened_at = Column(DateTime(timezone=True), server_default=func.now())
    closed_at = Column(DateTime(timezone=True))
    realized_pnl = Column(Float, default=0.0)
    unrealized_pnl = Column(Float, default=0.0)
    fees = Column(Float, default=0.0)
    exit_reason = Column(String(50))  # TP1, TP2, TP3, SL, CHoCH, BOS, MANUAL
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    exchange = relationship("Exchange", back_populates="positions")
    symbol = relationship("Symbol", back_populates="positions")
    orders = relationship("Order", back_populates="position")

    __table_args__ = (
        {'sqlite_autoincrement': True}
    )


class Trade(Base):
    """Individual trade/fill from exchange."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    trade_id = Column(String(100), unique=True)
    order_id = Column(Integer, ForeignKey("orders.id"), nullable=False)
    position_id = Column(Integer, ForeignKey("positions.id"))
    exchange_id = Column(Integer, ForeignKey("exchanges.id"), nullable=False)
    symbol_id = Column(Integer, ForeignKey("symbols.id"), nullable=False)
    side = Column(String(10), nullable=False)
    quantity = Column(Float, nullable=False)
    price = Column(Float, nullable=False)
    fee = Column(Float, default=0.0)
    fee_currency = Column(String(20))
    is_maker = Column(Boolean, default=False)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        {'sqlite_autoincrement': True}
    )


class RiskEvent(Base):
    """Risk management events."""
    __tablename__ = "risk_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    event_type = Column(String(50), nullable=False)  # MAX_TRADES, DAILY_DD, EXPOSURE, etc.
    symbol_id = Column(Integer, ForeignKey("symbols.id"))
    exchange_id = Column(Integer, ForeignKey("exchanges.id"))
    details = Column(JSON)
    blocked = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        {'sqlite_autoincrement': True}
    )


class SystemEvent(Base):
    """System-level events."""
    __tablename__ = "system_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    event_type = Column(String(50), nullable=False)  # START, STOP, ERROR, RECONCILIATION, etc.
    component = Column(String(50))  # ENGINE, EXCHANGE, STRATEGY, etc.
    severity = Column(String(20), default="INFO")  # INFO, WARNING, ERROR, CRITICAL
    message = Column(Text, nullable=False)
    details = Column(JSON)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        {'sqlite_autoincrement': True}
    )


class StrategySettings(Base):
    """Current strategy settings."""
    __tablename__ = "strategy_settings"

    id = Column(Integer, primary_key=True, autoincrement=True)
    version = Column(Integer, default=1)
    structure_period = Column(Integer, default=20)
    confirmation_type = Column(String(10), default="Body")  # Body, Wick
    htf1 = Column(String(10), default="4h")
    htf2 = Column(String(10), default="1d")
    adx_th = Column(Integer, default=20)
    adx_trend = Column(Integer, default=25)
    adx_dead = Column(Integer, default=15)
    filter_mode = Column(String(10), default="2of3")  # 2of3, ALL
    vol_mult = Column(Float, default=1.5)
    use_impulse = Column(Boolean, default=True)
    impulse_mult = Column(Float, default=1.0)
    use_range_bounce = Column(Boolean, default=True)
    bb_lookback = Column(Integer, default=10)
    max_bounces = Column(Integer, default=2)
    min_atr_pct = Column(Float, default=0.3)
    max_bos_dist_atr = Column(Float, default=0.5)
    use_cooldown = Column(Boolean, default=True)
    cooldown_bars = Column(Integer, default=6)
    risk_pct = Column(Float, default=1.0)
    tp1_pct = Column(Integer, default=40)
    tp2_pct = Column(Integer, default=30)
    tp3_pct = Column(Integer, default=30)
    use_breakeven = Column(Boolean, default=True)
    use_trail = Column(Boolean, default=False)
    trailing_offset = Column(Float, default=0.25)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    __table_args__ = (
        {'sqlite_autoincrement': True}
    )


class StrategySettingsHistory(Base):
    """History of strategy settings changes."""
    __tablename__ = "strategy_settings_history"

    id = Column(Integer, primary_key=True, autoincrement=True)
    settings_id = Column(Integer, ForeignKey("strategy_settings.id"), nullable=False)
    parameter = Column(String(50), nullable=False)
    old_value = Column(Text)
    new_value = Column(Text, nullable=False)
    changed_by = Column(String(50), default="user")  # user, api, system
    reason = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        {'sqlite_autoincrement': True}
    )
