"""
Core data models for ATS-SMT Pro Trading Bot.

These models are used throughout the system for type safety and validation.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum
from decimal import Decimal


# =============================================================================
# ENUMS
# =============================================================================

class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP_LOSS = "STOP_LOSS"
    STOP_LIMIT = "STOP_LIMIT"
    TAKE_PROFIT = "TAKE_PROFIT"


class OrderStatus(str, Enum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class PositionSide(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class SignalAction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    CLOSE_LONG = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"
    FLIP_TO_LONG = "FLIP_TO_LONG"
    FLIP_TO_SHORT = "FLIP_TO_SHORT"
    HOLD = "HOLD"


class MarketRegime(str, Enum):
    DEAD = "DEAD"
    RANGE = "RANGE"
    TREND = "TREND"


class TrendDirection(str, Enum):
    BULLISH = 1
    NEUTRAL = 0
    BEARISH = -1


class EngineState(str, Enum):
    STOPPED = "STOPPED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    ERROR = "ERROR"
    EMERGENCY = "EMERGENCY"


class TradingMode(str, Enum):
    PAPER = "PAPER"
    TESTNET = "TESTNET"
    LIVE = "LIVE"


# =============================================================================
# MARKET DATA MODELS
# =============================================================================

class Candle(BaseModel):
    """OHLCV candle model."""
    
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    
    @property
    def is_closed(self) -> bool:
        """Check if candle is closed (in real-time context)."""
        return datetime.utcnow() > self.timestamp
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class Ticker(BaseModel):
    """Real-time ticker data."""
    
    symbol: str
    last: float
    bid: float
    ask: float
    high_24h: float
    low_24h: float
    volume_24h: float
    change_24h: float
    timestamp: datetime


class SymbolInfo(BaseModel):
    """Exchange symbol/contract information."""
    
    symbol: str  # Canonical format: BTC/USDT
    exchange_symbol: str  # Exchange-specific: BTCUSDT
    base_currency: str
    quote_currency: str
    price_precision: int
    quantity_precision: int
    min_quantity: float
    max_quantity: float
    min_notional: float
    tick_size: float
    step_size: float
    is_active: bool


# =============================================================================
# STRATEGY MODELS
# =============================================================================

class PivotPoint(BaseModel):
    """Confirmed pivot high or low."""
    
    timestamp: datetime
    price: float
    pivot_type: str  # 'HIGH' or 'LOW'
    confirmed_at: datetime
    bar_index: int


class SwingLevel(BaseModel):
    """Confirmed swing high or low level."""
    
    price: float
    level_type: str  # 'HIGH' or 'LOW'
    timestamp: datetime
    confirmed: bool


class MarketStructure(BaseModel):
    """Current market structure state."""
    
    last_swing_high: Optional[float] = None
    last_swing_low: Optional[float] = None
    trend: int = 0  # -1, 0, +1
    structure_broken: bool = False


class HTFTrend(BaseModel):
    """Higher timeframe trend analysis."""
    
    trend_4h: int = 0  # -1, 0, +1
    trend_1d: int = 0  # -1, 0, +1
    combined_score: int = 0  # -2 to +2
    
    @property
    def is_bullish(self) -> bool:
        return self.combined_score > 0
    
    @property
    def is_bearish(self) -> bool:
        return self.combined_score < 0
    
    @property
    def is_neutral(self) -> bool:
        return self.combined_score == 0


class IndicatorValues(BaseModel):
    """Current indicator values for a symbol."""
    
    adx: float = 0.0
    atr: float = 0.0
    atr_pct: float = 0.0
    volume: float = 0.0
    volume_sma: float = 0.0
    volume_ratio: float = 1.0  # Added for strategy state tracking
    bb_upper: float = 0.0
    bb_middle: float = 0.0
    bb_lower: float = 0.0
    impulse: float = 0.0


class StrategySignal(BaseModel):
    """
    Trading signal generated by strategy core.
    
    This is the primary output of the strategy engine.
    Contains all information needed for risk assessment and order execution.
    """
    
    signal_id: str
    timestamp: datetime
    exchange: str
    symbol: str
    timeframe: str
    
    action: SignalAction
    
    # Entry/Exit levels
    entry_price: float
    stop_loss: float
    tp1: float
    tp2: float
    tp3: float
    
    # Strategy context
    regime: MarketRegime
    votes: int  # 0-3
    votes_required: int
    htf_4h: int  # -1, 0, +1
    htf_1d: int  # -1, 0, +1
    adx: float
    atr: float
    volume_ratio: float
    
    # Structure
    bos_detected: bool
    choch_detected: bool
    swing_level: float  # Entry reference
    
    # Risk
    risk_pct: float
    position_size: float
    risk_amount: float
    reward_ratio: float
    
    # Filters
    impulse_ok: bool
    atr_ok: bool
    bos_ok: bool
    cooldown_ok: bool
    range_conditions_ok: bool
    
    # Metadata
    strategy_version: str = "SMT_PRO_V2"
    confirmation_type: str = "BODY"  # BODY or WICK
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }
    
    @property
    def is_valid(self) -> bool:
        """Check if signal passes all filters."""
        return (
            self.action in [SignalAction.LONG, SignalAction.SHORT] and
            self.cooldown_ok and
            self.atr_ok and
            self.bos_ok and
            self.range_conditions_ok and
            self.votes >= self.votes_required
        )


# =============================================================================
# ORDER MODELS
# =============================================================================

class Order(BaseModel):
    """Order representation."""
    
    order_id: str
    client_order_id: str
    exchange: str
    symbol: str
    side: OrderSide
    type: OrderType
    quantity: float
    price: Optional[float] = None
    stop_price: Optional[float] = None
    filled_quantity: float = 0.0
    average_price: float = 0.0
    status: OrderStatus = OrderStatus.PENDING
    created_at: datetime
    updated_at: datetime
    exchange_order_id: Optional[str] = None
    
    # Strategy context
    strategy: str = "SMT_PRO"
    signal_id: Optional[str] = None
    position_id: Optional[str] = None
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class OrderRequest(BaseModel):
    """Order creation request."""
    
    exchange: str
    symbol: str
    side: OrderSide
    type: OrderType
    quantity: float
    price: Optional[float] = None
    stop_price: Optional[float] = None
    client_order_id: str
    signal_id: Optional[str] = None
    position_id: Optional[str] = None


# =============================================================================
# POSITION MODELS
# =============================================================================

class Position(BaseModel):
    """
    Active trading position.
    
    Tracks all aspects of an open position including partial closes,
    breakeven state, and trailing stop.
    """
    
    position_id: str
    exchange: str
    symbol: str
    side: PositionSide
    strategy: str
    
    # Size & Entry
    initial_quantity: float
    remaining_quantity: float
    entry_price: float
    actual_entry_price: float  # After fees/slippage
    
    # Exit levels
    stop_loss: float
    tp1: float
    tp2: float
    tp3: float
    
    # TP tracking
    tp1_hit: bool = False
    tp2_hit: bool = False
    tp3_hit: bool = False
    tp1_closed_qty: float = 0.0
    tp2_closed_qty: float = 0.0
    tp3_closed_qty: float = 0.0
    
    # Risk management
    initial_risk: float  # In price units
    risk_pct: float
    breakeven_active: bool = False
    trailing_active: bool = False
    trailing_stop_price: Optional[float] = None
    
    # State
    regime: MarketRegime
    opened_at: datetime
    closed_at: Optional[datetime] = None
    closed_reason: Optional[str] = None
    
    # PnL
    realized_pnl: float = 0.0
    unrealized_pnl: float = 0.0
    fees_paid: float = 0.0
    
    # References
    signal_id: str
    entry_order_id: Optional[str] = None
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }
    
    @property
    def is_closed(self) -> bool:
        return self.remaining_quantity <= 0
    
    @property
    def is_long(self) -> bool:
        return self.side == PositionSide.LONG
    
    @property
    def is_short(self) -> bool:
        return self.side == PositionSide.SHORT
    
    def get_current_pnl(self, current_price: float) -> float:
        """Calculate current PnL based on price."""
        if self.is_long:
            return (current_price - self.entry_price) * self.remaining_quantity
        else:
            return (self.entry_price - current_price) * self.remaining_quantity
    
    def get_pnl_percentage(self, current_price: float) -> float:
        """Calculate PnL as percentage of entry."""
        if self.is_long:
            return ((current_price - self.entry_price) / self.entry_price) * 100
        else:
            return ((self.entry_price - current_price) / self.entry_price) * 100
    
    def get_r_multiple(self, current_price: float) -> float:
        """Calculate R multiple (profit/loss relative to initial risk)."""
        pnl = self.get_current_pnl(current_price)
        if self.initial_risk == 0:
            return 0
        return pnl / (self.initial_risk * self.initial_quantity)


# =============================================================================
# PORTFOLIO MODELS
# =============================================================================

class Balance(BaseModel):
    """Account balance for a currency."""
    
    currency: str
    free: float
    locked: float
    total: float
    
    @property
    def available(self) -> float:
        return self.free


class PortfolioSummary(BaseModel):
    """Overall portfolio state."""
    
    total_equity: float
    total_balance: float
    available_balance: float
    invested: float
    unrealized_pnl: float
    realized_pnl: float
    daily_pnl: float
    daily_drawdown: float
    open_positions: int
    exposure_pct: float


# =============================================================================
# EXCHANGE MODELS
# =============================================================================

class ExchangeStatus(BaseModel):
    """Exchange connection status."""
    
    exchange: str
    connected: bool
    last_update: datetime
    latency_ms: int
    error_count: int
    rate_limit_remaining: int
    message: Optional[str] = None


# =============================================================================
# ENGINE MODELS
# =============================================================================

class EngineStatus(BaseModel):
    """Trading engine status."""
    
    state: EngineState
    mode: TradingMode
    uptime_seconds: float
    started_at: datetime
    last_signal: Optional[datetime] = None
    last_order: Optional[datetime] = None
    active_symbols: int
    open_positions: int
    errors: List[str] = []


class HealthStatus(BaseModel):
    """System health check result."""
    
    status: str  # HEALTHY, DEGRADED, ERROR
    engine_running: bool
    database_connected: bool
    exchanges_connected: int
    exchanges_total: int
    symbols_healthy: int
    symbols_total: int
    last_market_data_update: datetime
    last_strategy_calculation: datetime
    last_reconciliation: datetime
    errors: List[str] = []


# =============================================================================
# NOTIFICATION MODELS
# =============================================================================

class NotificationType(str, Enum):
    BOT_STARTED = "BOT_STARTED"
    BOT_STOPPED = "BOT_STOPPED"
    SIGNAL = "SIGNAL"
    ORDER_OPENED = "ORDER_OPENED"
    TP_HIT = "TP_HIT"
    SL_HIT = "SL_HIT"
    BREAKEVEN = "BREAKEVEN"
    STRUCTURE_EXIT = "STRUCTURE_EXIT"
    FLIP = "FLIP"
    ERROR = "ERROR"
    WARNING = "WARNING"


class Notification(BaseModel):
    """Notification for Telegram/API."""
    
    notification_type: NotificationType
    title: str
    message: str
    timestamp: datetime
    data: Optional[Dict[str, Any]] = None
    priority: str = "NORMAL"  # LOW, NORMAL, HIGH, CRITICAL
